01-config_swap: Always mount swap when it has been created.
Fix a bug where swap could be formatted but not actually mounted since
there was no call to swapon.

diff --git a/gandi-config/bootstrap.d/01-config_swap b/gandi-config/bootstrap.d/01-config_swap
--- a/gandi-config/bootstrap.d/01-config_swap
+++ b/gandi-config/bootstrap.d/01-config_swap
@@ -58,7 +58,16 @@ detect_blkid() {
     type=$(/sbin/blkid -s TYPE "$swap_device")
     ret=$?
     if [ $ret -eq 2 ]; then
-        ensure_safe "$1" && create_swap "$1"
+        if ensure_safe "$1"; then
+            create_swap "$1"
+            type=$(/sbin/blkid -s TYPE -o value "$1")
+            if [ $? -eq 0 ]; then
+                enable_swap "$1" "$type"
+            else
+                echo 'Undefined error during swap creation.' | logger
+                echo 'Undefined error during swap creation.' >&2
+            fi
+        fi
     elif [ $ret -eq 0 ]; then
         type=$(/sbin/blkid -s TYPE -o value "$1")
         enable_swap "$1" "$type"
