03-resize_main_disk: Add GPT partition resize.
Only resize partition when all above conditions are met:
 * /dev/xvda is a disk partitionned in GTP ;
 * its GPT backup header is not at the end of the disk (indicating the
   disk has been resized) ;
 * its last partition has label "gandiroot".
In this case, extend the last partition to the biggest possible size.

Randomize disk and partition GUIDs on first boot (if the disk GUID is
00000000-0000-0000-0000-000000000000).

diff --git a/gandi-config/bootstrap.d/03-resize_main_disk b/gandi-config/bootstrap.d/03-resize_main_disk
--- a/gandi-config/bootstrap.d/03-resize_main_disk
+++ b/gandi-config/bootstrap.d/03-resize_main_disk
@@ -9,6 +9,58 @@ if [ -z "$SYSLOG_TARGET" ]; then
     SYSLOG_TARGET='gandi'
 fi
 
+# If the last partition of the GPT disk has label gandiroot, resize it.
+disk=/dev/xvda
+if which sgdisk >/dev/null && [ -b "$disk" ]; then
+    disk_layout=$(sgdisk -p "$disk")
+    if [ $? -eq 0 ] && ! echo "${disk_layout}" | grep -qF 'Found invalid GPT'; then
+        # Disk is GPT
+        if sgdisk -v "$disk" | grep -qF 'secondary header'; then
+            # Disk has been extended
+            tmpfile=$(mktemp)
+            part_id=$(sgdisk -p "$disk" | tail -n1 | sed 's/^ *\([0-9]*\) .*$/\1/')
+            sgdisk -i "$part_id" "$disk" >"$tmpfile"
+            part_begin=$(sed -n 's/^First sector: \([0-9]*\) .*$/\1/p' "$tmpfile")
+            part_attributes=$(sed -n 's/^Attribute flags: \([0-9A-F]*\)$/\1/p' "$tmpfile")
+            part_guid_code=$(sed -n 's/^Partition GUID code: \([0-9A-F-]*\) .*$/\1/p' "$tmpfile")
+            part_unique_guid=$(sed -n 's/^Partition unique GUID: \([0-9A-F-]*\)$/\1/p' "$tmpfile")
+            part_name=$(sed -n "s/^Partition name: '\\(.*\\)'$/\\1/p" "$tmpfile")
+            if [ "$part_name" = 'gandiroot' ]; then
+                if ! sgdisk --move-second-header \
+                        --delete "$part_id" \
+                        --new="${part_id}:${part_begin}:0" \
+                        --attributes="${part_id}:=:${part_attributes}" \
+                        --change-name="${part_id}:${part_name}" \
+                        --partition-guid="${part_id}:${part_unique_guid}" \
+                        --typecode="${part_id}:${part_guid_code}" \
+                        "$disk" 2>&1 | logger -t "$SYSLOG_TARGET"; then
+                    err_code="$?"
+                    loginfo "Error resizing partition ${part_id} of GPT disk " \
+                            "${disk}, return: ${err_code}"
+                    exit "$err_code"
+                fi
+            fi
+            rm "$tmpfile"
+        fi
+        # Reset all GUIDs if disk GUID is null (on first boot)
+        disk_guid=$(sgdisk -p "$disk" | sed -n 's/^Disk identifier (GUID): \([0-9A-F-]*\)$/\1/p')
+        if [ "$disk_guid" = '00000000-0000-0000-0000-000000000000' ]; then
+            if ! sgdisk --randomize-guids "$disk" 2>&1 | logger -t "$SYSLOG_TARGET"; then
+                err_code="$?"
+                loginfo "Error randomizing GPT UIDs on disk ${disk}, return: ${err_code}"
+                exit "$err_code"
+            fi
+        fi
+        # Inform kernel of partition changes.
+        if ! partx --update "$disk" 2>&1 | logger -t "$SYSLOG_TARGET"; then
+            err_code="$?"
+            loginfo "Error updating in-kernel partition layout for disk " \
+                "${disk}, return: ${err_code}"
+            exit "$err_code"
+        fi
+    fi
+fi
+
 device=/dev/xvda1
 if [ ! -d /proc/xen ]; then
     device=/dev/sda
